Repository macromaster-app/web-app, pull requests merged in 2023-12, with the labels that each got.

#3 Date picker
  package.json
  src/app/tracker/page.tsx
  src/components/DatePicker/CalendarPagination.tsx
  src/components/DatePicker/CarouselPagination.tsx
  src/components/DatePicker/index.tsx
  src/components/MealList/index.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  tailwind.config.ts
  yarn.lock
Labels: feature, component

#6 Trpc setup
  next.config.js
  package.json
  src/app/_trpc/TRPCProvider.tsx
  src/app/_trpc/client.ts
  src/app/_trpc/serverClient.ts
  src/app/api/trpc/[trpc]/route.ts
  src/app/layout.tsx
  src/app/tracker/page.tsx
  src/server/index.ts
  src/server/trpc.ts
  yarn.lock
Labels: feature, config

#7 Prisma basic setup
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: config
